version: "3.7"
services:
  api_service:
    build: .
    restart: always
    stdin_open: true
    tty: true      
    ports:
      - 8080:8080
    environment:
    - JVM_OPTS=-Xms3G -Xmx3G
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
